const products = [
  {
    _id: '1',
    name: 'Airpods',
    image: '/images/airpods.jpg',
    description: 'sdasfsafasfsafas',
    brand: 'Apple',
    category: 'Elevctronics',
    price: 89.99,
    countInStock: 10,
    numReviews: 12,
    rating: 4.5,
  },
  {
    _id: '2',
    name: 'alexa',
    image: '/images/alexa.jpg',
    description: 'sdasfsafasfsafas',
    brand: 'Amazon',
    category: 'Elevctronics',
    price: 89.99,
    countInStock: 10,
    numReviews: 12,
    rating: 4.5,
  },
  {
    _id: '3',
    name: 'camera',
    image: '/images/camera.jpg',
    description: 'sdasfsafasfsafas',
    brand: 'Apple',
    category: 'Elevctronics',
    price: 89.99,
    countInStock: 10,
    numReviews: 12,
    rating: 4.5,
  },
  {
    _id: '4',
    name: 'mouse',
    image: '/images/mouse.jpg',
    description: 'sdasfsafasfsafas',
    brand: 'Apple',
    category: 'Elevctronics',
    price: 89.99,
    countInStock: 10,
    numReviews: 12,
    rating: 4.5,
  },
  {
    _id: '5',
    name: 'phone',
    image: '/images/phone.jpg',
    description: 'sdasfsafasfsafas',
    brand: 'Apple',
    category: 'Elevctronics',
    price: 89.99,
    countInStock: 10,
    numReviews: 12,
    rating: 4.5,
  },
  {
    _id: '6',
    name: 'playstation',
    image: '/images/playstation.jpg',
    description: 'sdasfsafasfsafas',
    brand: 'Apple',
    category: 'Elevctronics',
    price: 89.99,
    countInStock: 10,
    numReviews: 12,
    rating: 2.5,
  },
];

export default products;
